apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1dhy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-1dhy@sha256:20fba2f509fcf572f6a9eb33fe25daae8bf3ee7a4c0cce5e70eed09b37de34a0
        name: my-nodejs
        resources: {}
status: {}
